*[HTTP]: Hypertext Transfer Protocol
*[RCP]: Rich Client Platform
*[IDE]: Integrated Development Environment
*[JAR]: Java Archive
*[LSP]: Language Server Protocol
*[UI]: User Interface
*[UX]: User Experience
*[PSI]: Program Structure Interface
*[AST]: Abstract Syntax Tree
*[DOM]: Document Object Model
*[EDT]: Event Dispatch Thread
*[EP]: Extension Point
*[ES]: External System
*[FBI]: File Based Index
*[LVCS]: Local History
*[LaF]: Look and Feel
*[JPS]: JetBrains Project System
*[JBR]: JetBrains Runtime
*[PSI]: Program Structure Interface
*[RC]: Run Configuration
*[SSR]: Structural Search and Replace
*[UAST]: Unified Abstract Syntax Tree
*[VCS]: Version Control System
*[VF]: Virtual File
*[VFS]: Virtual File System
*[REST]: Representational State Transfer

*[MPS]: Meta Programming System
*[SNode]: Semantic Node
*[SRepository]: Semantic Repository
*[BaseLanguage]: a projectional clone of Java 6 (with optional extensions for Java 7 and 8)
*[DSL]: Domain Specific Language
*[JCEF]: Java Chromium Embedded Framework
*[NPE]: NullPointerException
*[JDK]: Java Development Kit
*[JRE]: Java Runtime Environment

*[OS]: Open Source
*[PR]: Pull Request or Public Relations
*[MDD]: Model Driven Development
*[M2M]: Model to Model
*[M2T]: Model to Text
*[MDSD]: Model Driven Software Development
*[NDA]: Non Disclosure Agreement
*[IETS3]: Integrated Specification Environment for the Specification of Technical Software Systems
*[UML]: Unified Markup Language
*[JVM]: Java Virtual Machine
*[AI]: Artificial Intelligence
*[SSH]: Secure Shell

*[FJ]: ForkJoin