site_name: mps-gotchas

# Meta tags (placed in header)
site_description: This website describes gotchas when working with MPS and gives some hints on how to write clean code in MPS.
site_author: Alexander Pann
site_url: https://alexanderpann.github.io/mps-gotchas

# Repository (add link to repository on each page)
repo_name: mps-gotchas
repo_url: https://github.com/alexanderpann/mps-gotchas
edit_uri: edit/main/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2022 Alexander Pann'

# Material theme
theme:
  name: 'material'
  palette:
    - primary: light green
    - accent: indigo

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - header.autohide
    - content.code.annotate
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

#plugins:
#  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata
plugins:
  - search
  - git-revision-date-localized
  - kroki

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
nav:
  - Home:
    - Welcome: index.md
    - General: gotchas/general/index.md
    - Plugins: gotchas/plugins/index.md
    - External Files and Tools: gotchas/external_files_and_tools/index.md
    - Console: gotchas/console/index.md
    - Build: gotchas/build/index.md
    - Miscellaneous: gotchas/misc/index.md
  - Aspects:
    - Structure: gotchas/aspects/structure/index.md
    - Editor: gotchas/aspects/editor/index.md
    - Constraints: gotchas/aspects/constraints/index.md
    - Behaviour: gotchas/aspects/behavior/index.md
    - Actions: gotchas/aspects/actions/index.md
    - Typesystem: gotchas/aspects/typesystem/index.md
    - Intentions: gotchas/aspects/intentions/index.md
    - Migrations: gotchas/aspects/migrations/index.md
    - Generator: gotchas/aspects/generator/index.md
    - Plugin: gotchas/aspects/plugin/index.md
    - TextGen: gotchas/aspects/textGen/index.md
    - Tests: gotchas/aspects/tests/index.md
    - Dataflow: gotchas/aspects/dataFlow/index.md
    - Feedback: gotchas/aspects/feedback/index.md
    - Refactorings: gotchas/aspects/refactorings/index.md
    - Find Usages: gotchas/aspects/findUsages/index.md
    - VCS: gotchas/aspects/vcs/index.md
    - Scripts: gotchas/aspects/scripts/index.md
    - Contributed Aspects:
      - Listener*: gotchas/aspects/listener/index.md
      - Documentation*: gotchas/aspects/documentation/index.md
      - Polyfun*: gotchas/aspects/polyfun/index.md
      - Virtual Interfaces*: gotchas/aspects/virtualinterfaces/index.md
      - Transformations*: gotchas/aspects/transformations/index.md
  - Languages:
      - Info: gotchas/languages/index.md
      - Base Language and Extensions: gotchas/languages/baselanguage.md
      - MPS Extensions: gotchas/languages/mps_extensions.md
      - Mbeddr: gotchas/languages/mbeddr_mpsutil.md
      - Double dispatch: gotchas/languages/double_dispatch.md
  - Mbeddr:
      - BigProject: mbeddr/big_project.md
      - Development Guide: mbeddr/development_guide.md
      - Miscellaneous topics: mbeddr/misc_topics.md
  - Internal MPS:
      - General: gotchas/mps_internal/index.md
      - GUI: gotchas/mps_internal/gui.md
  - Clean code:
      - General: clean_code/mps/general.md
      - Miscellaneous: clean_code/mps/misc.md
      - Deprecation: clean_code/deprecation.md
      - Base language:
        - General: clean_code/baselanguage/general.md
        - Programming principles: clean_code/programming_principles.md
        - Java Style Guide: clean_code/baselanguage/java_style_guide.md
  - Reference:
    - Reading List: reference/reading_list.md
    - Icons: reference/icons.md
    - Exceptions: reference/exceptions.md
    - Actions: reference/actions.md
