site_name: MPS Platform Docs

site_description: This website answers some common questions about MPS and shows common gotchas and pitfalls when working with MPS and common MPS platforms.
site_author: itemis platform team
site_url: https://mbeddr.github.io/mps-platform-docs

repo_name: mps-platform-docs
repo_url: https://github.com/mbeddr/mps-platform-docs
edit_uri: edit/main/src/doc/docs/

copyright: 'Copyright &copy; 2022 itemis platform team'

theme:
  name: 'material'
  palette:
    - primary: light green
    - accent: indigo

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - header.autohide
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  mps_latest: MPS 2021.3.1
  mps_author: MPS 2021.1.4

plugins:
  - search
  - macros
  - git-revision-date-localized
  - kroki
  - autolinks
  - autolink_references:
      autolinks:
        - reference_prefix: MPS-
          target_url: https://youtrack.jetbrains.com/issue/MPS-<num>
        - reference_prefix: IDEABKL-
          target_url: https://youtrack.jetbrains.com/issue/IDEABKL-<num>
        - reference_prefix: JBR-
          target_url: https://youtrack.jetbrains.com/issue/JBR-<num>
        - reference_prefix: IDEA-
          target_url: https://youtrack.jetbrains.com/issue/IDEA-<num>
        - reference_prefix: IJSDK-
          target_url: https://youtrack.jetbrains.com/issue/IJSDK-<num>
        - reference_prefix: MBEDDR-
          target_url: https://github.com/mbeddr/mbeddr.core/issues/<num>
        - reference_prefix: MPS_EXTENSIONS-
          target_url: https://github.com/JetBrains/MPS-extensions/issues/<num>
        - reference_prefix: IETS3-
          target_url: https://github.com/IETS3/iets3.opensource/issues/<num>

markdown_extensions:
  - abbr
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
        auto_append:
           - includes/abbreviations.inc
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
nav:
  - Home:
    - index.md
    - General: home/general.md
    - Plugins: home/plugins.md
    - External Files and Tools: home/external_files_and_tools.md
    - Console: home/console.md
    - Platform specific:
      - Windows: home/platforms/windows.md
      - Mac: home/platforms/mac.md
      - Linux: home/platforms/linux.md
    - RCP: home/rcp.md
    - Trouble Shooting Guide: home/trouble_shooting_guide.md
    - Debugging: home/debugging.md
  - Aspects:
    - Structure: aspects/structure.md
    - Editor: aspects/editor.md
    - Actions: aspects/actions.md
    - Constraints: aspects/constraints.md
    - Behaviour: aspects/behavior.md
    - Feedback: aspects/feedback.md
    - Typesystem: aspects/typesystem.md
    - Refactorings: aspects/refactorings.md
    - Scripts: aspects/scripts.md
    - Intentions: aspects/intentions.md
    - Find Usages: aspects/findusages.md
    - Plugin: aspects/plugin.md
    - Dataflow: aspects/dataflow.md
    - Test: aspects/test.md
    - TextGen: aspects/textgen.md
    - Migration: aspects/migration.md
    - VCS: aspects/vcs.md
    - Generator: aspects/generator.md
    - Contributed Aspects:
      - Documentation: aspects/documentation.md
      - Listener: aspects/listener.md
      - Polyfun: aspects/polyfun.md
      - Virtual Interfaces: aspects/virtualinterfaces.md
      - Transformations: aspects/transformations.md
  - Languages:
      - languages/index.md
      - Baselanguage and Extensions: languages/baselanguage.md
      - MPS Extensions: languages/mps_extensions.md
      - Double dispatch: languages/double_dispatch.md
  - Mbeddr:
      - mbeddr/index.md
      - BigProject: mbeddr/big_project.md
      - Development Guide: mbeddr/development_guide.md
      - Miscellaneous topics: mbeddr/misc_topics.md
  - Build:
      - Build: build/index.md
      - CI: build/ci.md
      - Gradle: build/gradle.md
      - Creating a command line tool: build/command_line_tool.md
      - Git: build/git.md
  - Internal MPS:
      - mps_internal/index.md
      - Open API: mps_internal/open_api.md
      - Dependencies and Classpath:
        - General: mps_internal/deps_and_classpath/index.md
        - Terminology and UI for Access: mps_internal/terminology_and_ui_for_access.md
        - Models: mps_internal/models.md
        - Dependencies: mps_internal/dependencies.md
        - Recipes: mps_internal/recipes.md
      - Classloading: mps_internal/classloading.md
      - Utility classes: mps_internal/utility_classes.md
      - GUI: mps_internal/gui.md
      - IntelliJ SDK: mps_internal/intellij_sdk.md
  - Clean code:
      - clean_code/mps/index.md
      - Readability/maintainability: clean_code/mps/readability_maintainability.md
      - Deprecation: clean_code/mps/deprecation.md
      - Java (Baselanguage):
        - clean_code/java/index.md
        - Programming principles: clean_code/java/programming_principles.md
        - Java Style Guide: clean_code/java/java_style_guide.md
  - Language and UI Patterns:
      - Language design: patterns/language_design.md
      - User experience: patterns/user_experience.md
      - UI patterns: patterns/ui_patterns.md
  - Reference:
    - Reading List: reference/reading_list.md
    - Icons: reference/icons.md
    - Exceptions: reference/exceptions.md
    - Actions: reference/actions.md
  - About:
    - Editing this guide: reference/editing_this_guide.md
    - Original authors: reference/original_authors.md