site_name: MPS Platform Docs
site_description: This website collects practical knowlege about MPS and popular MPS platforms such as MPS-extensions and mbeddr. It is written mainly in the form of a Q&A.
site_author: MPS Platform Docs team
site_url: https://mbeddr.github.io/mps-platform-docs

repo_name: mps-platform-docs
repo_url: https://github.com/mbeddr/mps-platform-docs
edit_uri: edit/main/src/doc/docs/

theme:
  name: 'material'
  palette:
    - primary: light green
    - accent: indigo

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - header.autohide
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss

  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  mps_latest: MPS 2021.3.1
  mps_author: MPS 2021.1.4

plugins:
  - search:
      separator: '(?!MPS)[\s\-/#:]'
  - macros:
      on_error_fail: true
  - gen-files:
      scripts:
          - gen_abbreviations.py
  - git-revision-date-localized:
      exclude:
        - includes/abbreviations.md
        - reference/abbreviations.md
        - includes/code_abbreviations.md
        - reference/code_abbreviations.md
  - kroki
  - glightbox:
      width: 70vw
      height: 20vw
      selector: .glightbox
  - autolinks
  - autolink_references:
      autolinks:
        - reference_prefix: MPS-
          target_url: https://youtrack.jetbrains.com/issue/MPS-<num>
        - reference_prefix: IDEABKL-
          target_url: https://youtrack.jetbrains.com/issue/IDEABKL-<num>
        - reference_prefix: JBR-
          target_url: https://youtrack.jetbrains.com/issue/JBR-<num>
        - reference_prefix: IDEA-
          target_url: https://youtrack.jetbrains.com/issue/IDEA-<num>
        - reference_prefix: IJSDK-
          target_url: https://youtrack.jetbrains.com/issue/IJSDK-<num>
        - reference_prefix: MBEDDR-
          target_url: https://github.com/mbeddr/mbeddr.core/issues/<num>
        - reference_prefix: MPS_EXTENSIONS-
          target_url: https://github.com/JetBrains/MPS-extensions/issues/<num>
        - reference_prefix: IETS3-
          target_url: https://github.com/IETS3/iets3.opensource/issues/<num>

markdown_extensions:
  - mdx_spanner
  - abbr
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets:
        auto_append:
           - docs/includes/abbreviations.md
           - docs/includes/code_abbreviations.md
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home:
    - index.md
    - General: home/general.md
    - Plugins: home/plugins.md
    - External files and tools: home/external_files_and_tools.md
    - Console: home/console.md
    - OS-specific bugs: home/platform_specific_bugs.md
    - RCP: home/rcp.md
    - Trouble shooting guide: home/trouble_shooting_guide.md
    - Visual guide: home/visual_guide.md
    - Debugging: home/debugging.md
  - Aspects:
    - Structure: aspects/structure.md
    - Editor: aspects/editor.md
    - Actions: aspects/actions.md
    - Constraints: aspects/constraints.md
    - Behavior: aspects/behavior.md
    - Feedback: aspects/feedback.md
    - Typesystem: aspects/typesystem.md
    - Refactorings: aspects/refactorings.md
    - Scripts: aspects/scripts.md
    - Intentions: aspects/intentions.md
    - Find Usages: aspects/findusages.md
    - Plugin: aspects/plugin.md
    - Dataflow: aspects/dataflow.md
    - Test: aspects/test.md
    - TextGen: aspects/textgen.md
    - Migration: aspects/migration.md
    - VCS: aspects/vcs.md
    - Generator: aspects/generator.md
    - Contributed aspects:
      - Documentation: aspects/documentation.md
      - Listener: aspects/listener.md
      - Polyfun: aspects/polyfun.md
      - Virtual Interfaces: aspects/virtualinterfaces.md
      - Transformations: aspects/transformations.md
  - Languages:
      - languages/index.md
      - Baselanguage and extensions: languages/baselanguage.md
      - MPS-extensions: languages/mps_extensions.md
      - Double dispatch: languages/double_dispatch.md
  - Mbeddr:
      - mbeddr/index.md
      - BigProject: mbeddr/big_project.md
      - Development guide: mbeddr/development_guide.md
      - Miscellaneous topics: mbeddr/misc_topics.md
  - Build:
      - Build: build/index.md
      - CI: build/ci.md
      - Gradle: build/gradle.md
      - Creating a command line tool: build/command_line_tool.md
      - Git: build/git.md
  - Internal MPS:
      - mps_internal/index.md
      - Open API: mps_internal/open_api.md
      - Dependencies and classpath:
        - General: mps_internal/deps_and_classpath/index.md
        - Terminology and UI for access: mps_internal/terminology_and_ui_for_access.md
        - Models: mps_internal/models.md
        - Dependencies: mps_internal/dependencies.md
        - Recipes: mps_internal/recipes.md
      - Classloading: mps_internal/classloading.md
      - Threading:
          - mps_internal/threads/index.md
          - Example actions using locks: mps_internal/threads/read_write_action_examples.md
          - Named threads: mps_internal/threads/named_threads.md
      - Utility classes: mps_internal/utility_classes.md
      - GUI: mps_internal/gui.md
      - IntelliJ SDK: mps_internal/intellij_sdk.md
      - Java Chromium Embedded Framework: mps_internal/jcef.md
      - Writing an MPS plugin with Kotlin: mps_internal/writing_mps_plugin_with_kotlin.md 
      - IntelliJ integration: mps_internal/intellij_integration.md 
      - Navigating the MPS sources: mps_internal/navigating_mps_source.md
  - Platform essentials:
      - platform_essentials/index.md
      - Contributing: platform_essentials/contributing.md
      - Common concepts and interfaces: platform_essentials/common_concepts_and_interfaces.md
      - Interpreter: platform_essentials/interpreter.md
      - Building Mbeddr locally: platform_essentials/building_mbeddr_locally.md
      - Platform build scripts: platform_essentials/platform_build_scripts.md  
  - Clean code:
      - clean_code/mps/index.md
      - Readability/maintainability: clean_code/mps/readability_maintainability.md
      - Deprecation: clean_code/mps/deprecation.md
      - Java (Base Language):
        - clean_code/java/index.md
        - Programming principles: clean_code/java/programming_principles.md
        - Java style guide: clean_code/java/java_style_guide.md
  - Language/UI patterns:
      - Language design: patterns/language_design.md
      - User experience: patterns/user_experience.md
      - UI patterns: patterns/ui_patterns.md
  - Reference:
    - Reading list: reference/reading_list.md
    - Tips for open source maintainers: reference/tips_for_os_maintainers.md
    - Icons: reference/icons.md
    - Core languages: reference/core_languages.md  
    - Extension points: reference/extension_points.md
    - Exceptions: reference/exceptions.md
    - Actions: reference/actions.md
    - Abbreviations: reference/abbreviations.md 
    - Code abbreviations: reference/code_abbreviations.md
    - Gitignore file: reference/gitignore.md
    - Issue trackers: reference/issue_trackers.md
  - About:
    - Editing this guide: about/editing_this_guide.md
    - Original authors: about/original_authors.md
    - New pages: home/new_pages.md