site_name: MPS Platform Docs
site_description: This website collects practical knowledge about MPS and popular MPS platforms such as MPS-extensions and mbeddr. It is written mainly in the form of a Q&A.
site_author: MPS Platform Docs team
site_url: http://mbeddr.com/mps-platform-docs/

repo_name: mps-platform-docs
repo_url: https://github.com/mbeddr/mps-platform-docs
edit_uri: edit/main/src/doc/docs/

theme:
  name: 'material'
  palette:
    - primary: light green
    - accent: indigo

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - header.autohide
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.code.copy
    - navigation.prune
  
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/code_scrolling.js
  - javascripts/mathjax.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  mps_latest: MPS 2022.2
  mps_author: MPS 2021.1.4
  analytics:
    provider: google
    property: G-3FEXS9GHRT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - macros:
      on_error_fail: true
  - gen-files:
      scripts:
          - gen_abbreviations.py
  - git-revision-date-localized:
      exclude:
        - includes/abbreviations.md
        - reference/abbreviations.md
        - includes/code_abbreviations.md
        - reference/code_abbreviations.md
  - kroki
  - tags:
      tags_file: tags.md
  - glightbox:
      width: 100%
      height: auto
      selector: .glightbox
  - autolinks
  - alias:
      use_relative_link: true
  - webcontext:
      context: mps-platform-docs
  - redirects:
      redirect_maps:
        'mps_internal/jcef.md': 'mps_internal/intellij_sdk/jcef.md'
  - autolink_references:
      autolinks:
        - reference_prefix: MPS-
          target_url: https://youtrack.jetbrains.com/issue/MPS-<num>
        - reference_prefix: IDEABKL-
          target_url: https://youtrack.jetbrains.com/issue/IDEABKL-<num>
        - reference_prefix: JBR-
          target_url: https://youtrack.jetbrains.com/issue/JBR-<num>
        - reference_prefix: IDEA-
          target_url: https://youtrack.jetbrains.com/issue/IDEA-<num>
        - reference_prefix: IJSDK-
          target_url: https://youtrack.jetbrains.com/issue/IJSDK-<num>
        - reference_prefix: MBEDDR-
          target_url: https://github.com/mbeddr/mbeddr.core/issues/<num>
        - reference_prefix: MPS_EXTENSIONS-
          target_url: https://github.com/JetBrains/MPS-extensions/issues/<num>
        - reference_prefix: IETS3-
          target_url: https://github.com/IETS3/iets3.opensource/issues/<num>

markdown_extensions:
  - mdx_spanner
  - abbr
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets:
        auto_append: !ENV [SNIPPET_APPENDS, ["docs/includes/abbreviations.md","docs/includes/code_abbreviations.md"]]
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home:
    - index.md
    - General: home/general.md
    - Plugins: home/plugins.md
    - External files and tools: home/external_files_and_tools.md
    - Console: home/console.md
    - OS-specific bugs: home/platform_specific_bugs.md
    - RCP: home/rcp.md
    - Trouble shooting guide: home/trouble_shooting_guide.md
    - Overcoming obstacles: 
      - Introduction to overcoming obstacles: home/overcoming_obstacles/overcoming_obstacles.md
      - Understanding the problem: home/overcoming_obstacles/understanding_the_problem.md
      - Debugging problems: home/overcoming_obstacles/debugging_problems.md
      - Syntax problems: home/overcoming_obstacles/syntax_problems.md
      - Thinking problems: home/overcoming_obstacles/thinking_problems.md
      - General tips: home/overcoming_obstacles/general_tips.md
    - Visual guide: home/visual_guide.md
    - Debugging: home/debugging.md
    - Performance: home/performance.md
  - Aspects:
    - Structure: aspects/structure.md
    - Editor: aspects/editor.md
    - Actions: aspects/actions.md
    - Constraints: aspects/constraints.md
    - Behavior: aspects/behavior.md
    - Feedback: aspects/feedback.md
    - Typesystem: aspects/typesystem.md
    - Refactorings: aspects/refactorings.md
    - Scripts: aspects/scripts.md
    - Intentions: aspects/intentions.md
    - Find Usages: aspects/findusages.md
    - Plugin: aspects/plugin.md
    - Dataflow: aspects/dataflow.md
    - Test: aspects/test.md
    - TextGen: aspects/textgen.md
    - Migration: aspects/migration.md
    - VCS: aspects/vcs.md
    - Generator: aspects/generator.md
    - Accessory models: aspects/accessory_models.md
    - Contributed aspects:
      - Documentation: aspects/documentation.md
      - Listener: aspects/listener.md
      - Polyfun: aspects/polyfun.md
      - Virtual Interfaces: aspects/virtualinterfaces.md
      - Transformations: aspects/transformations.md
  - Languages:
      - languages/index.md
      - Baselanguage and extensions: languages/baselanguage.md
      - Double dispatch: languages/double_dispatch.md
      - MPS-extensions: 
          - General: languages/mps_extensions.md
          - Cell Layout: languages/cell_layout.md
      - KernelF: languages/kernelf.md
  - Platform essentials:
      - platform_essentials/index.md
      - How everything is connected: platform_essentials/how_everything_is_connected.md
      - Contributing: platform_essentials/contributing.md
      - Common concepts and interfaces: platform_essentials/common_concepts_and_interfaces.md
      - Interpreter, coverage and tracing: platform_essentials/interpreter.md
      - Platform build scripts: platform_essentials/platform_build_scripts.md
      - Build folder: platform_essentials/build_folder.md
      - Testing: platform_essentials/testing.md
      - Accessing the project: platform_essentials/accessing_the_project.md
  - Build:
      - Build: build/index.md
      - CI: build/ci.md
      - Gradle: build/gradle.md
      - Creating a command line tool: build/command_line_tool.md
      - Git: build/git.md
      - TeamCity: build/teamcity.md
      - Advanced GitHub workflow: build/advanced_github_workflow.md
  - MPS internals:
      - mps_internal/index.md
      - Code:
          - Open API: mps_internal/open_api.md
          - Utility classes: mps_internal/utility_classes.md
          - Navigating the MPS sources: mps_internal/navigating_mps_source.md
          - Writing an MPS plugin with Kotlin: mps_internal/writing_mps_plugin_with_kotlin.md
      - UI:
          - Editor development: mps_internal/editor_development.md
          - IntelliJ UI: mps_internal/gui.md
          - Platform UI inspector : mps_internal/platform_ui_inspector.md
      - IntelliJ SDK: 
          - mps_internal/intellij_sdk.md
          - IntelliJ integration: mps_internal/intellij_integration.md
          - Java Chromium Embedded Framework: mps_internal/intellij_sdk/jcef.md
      - Advanced topics:
          - What happens on MPS startup : mps_internal/mps_startup.md
          - Dependencies and classpath:
              - General: mps_internal/deps_and_classpath/index.md
              - Terminology and UI for access: mps_internal/terminology_and_ui_for_access.md
              - Models: mps_internal/models.md
              - Dependencies: mps_internal/dependencies.md
              - Recipes: mps_internal/recipes.md
          - Classloading: mps_internal/classloading.md
          - Threading:
              - mps_internal/threads/index.md
              - Example actions using locks: mps_internal/threads/read_write_action_examples.md
              - Named threads: mps_internal/threads/named_threads.md
      - Reference:
        - File format: mps_internal/file_format.md
        - Java design patterns in the MPS sources: mps_internal/java_design_patterns_in_mps_sources.md
  - Mbeddr:
      - mbeddr/index.md
      - Building Mbeddr locally: mbeddr/building_mbeddr_locally.md
      - Mbeddr utilities:
          - platform_essentials/mpsutils/index.md
          - Common: platform_essentials/mpsutils/common.md
          - Actions: platform_essentials/mpsutils/actions.md
          - BaseLanguage extensions: platform_essentials/mpsutils/baselanguage_extensions.md
          - Generator: platform_essentials/mpsutils/generator.md
          - Importer and exporter: platform_essentials/mpsutils/importer_and_exporter.md
          - Languages: platform_essentials/mpsutils/languages.md
          - Language extensions: platform_essentials/mpsutils/language_extensions.md
          - Tools: platform_essentials/mpsutils/tools.md
          - UI: platform_essentials/mpsutils/ui.md
          - Testing: platform_essentials/mpsutils/testing.md
          - Plugin and RCP: platform_essentials/mpsutils/plugin_and_rcp.md
          - Deprecated languages and solutions: platform_essentials/mpsutils/deprecated.md
      - Mbeddr Doc documentation: http://mbeddr.com/files/documentationdocumentation.pdf
      - BigProject: mbeddr/big_project.md
      - Development guide: mbeddr/development_guide.md
      - Miscellaneous topics: mbeddr/misc_topics.md
  - Clean code:
      - clean_code/mps/index.md
      - Readability/maintainability: clean_code/mps/readability_maintainability.md
      - Deprecation: clean_code/mps/deprecation.md
      - Java (Base Language):
        - clean_code/java/index.md
        - Programming principles: clean_code/java/programming_principles.md
        - Java style guide: clean_code/java/java_style_guide.md
  - Language/UI patterns:
      - Language design: patterns/language_design.md
      - User experience: patterns/user_experience.md
      - UI patterns: patterns/ui_patterns.md
  - Reference:
    - Being a good developer: reference/being_a_good_developer.md
    - Tips for open source maintainers: reference/tips_for_os_maintainers.md
    - Icons: reference/icons.md
    - Core languages: reference/core_languages.md
    - Standard plugins: reference/standard_plugins.md
    - Included libraries: reference/included_libraries.md
    - Extension points: reference/extension_points.md
    - Exceptions: reference/exceptions.md
    - Actions: reference/actions.md
    - Abbreviations: reference/abbreviations.md
    - Code abbreviations: reference/code_abbreviations.md
    - Gitignore file: reference/gitignore.md
    - Issue trackers: reference/issue_trackers.md
  - Language Reference (WIP):
    - language_reference/index.md
    - org.iets3.core.expr.base: language_reference/org.iets3.core.expr.base.md
    - org.iets3.core.expr.collections: language_reference/org.iets3.core.expr.collections.md
    - org.iets3.core.expr.toplevel: language_reference/org.iets3.core.expr.toplevel.md
  - About:
    - Editing this guide: about/editing_this_guide.md
    - Original authors: about/original_authors.md
    - New pages: about/new_pages.md
    - Tags: tags.md
